### ISSUE TITLE
Default rotation speed causes robot to fall over in subt simulation

### ISSUE THREAD

**Issue by heuristicus** [leggedrobotics/cerberus_anymal_locomotion#7]
I have been testing the basic control commands in the subt simulator with the PR at https://github.com/osrf/subt/pull/383, following instructions in the readme to set up this package. As I understand from https://github.com/osrf/subt/blob/model_pr_434/submitted_models/cerberus_anymal_sensor_config_1/specifications.md, the motion commands have a fixed velocity.

In my case, the velocity rotation is much too high, causing the robot to consistently fall over after a few seconds of rotation.

I send

```
rostopic pub /anymal/cmd_vel geometry_msgs/Twist "linear:
  x: 0
  y: 0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.2"
```

Which appears to be the minimum `angular.z` which makes the robot rotate. Below is a gif of the result. So far this has happened 5/5 times where I have sent a rotation command while testing.

Can you suggest any reason why this might be happening? The translational velocity seems to be reasonable and the robot doesn't fall over.

![anymal_fallover](https://user-images.githubusercontent.com/636456/79986719-68719a80-84a4-11ea-99c7-c2634318e621.gif)

**Comment by lorenwel** [comment]
Hi, 

can the simulator keep up with real-time? Could you slow down the simulation speed and check if the issue persists?

**Comment by heuristicus** [comment]
The RTF displayed has large variance. Anything between 20% and 90%.

I'm pretty new to using ignition so I'm not sure where I could slow things down. What would be the best way to achieve a slower simulation rate?

I tried changing the `real_time_factor` in the `.sdf` of the world I was using, tried both simple_tunnel_01 and tunnel_circuit_practice_01, but it didn't seem to change anything.

**Comment by lorenwel** [comment]
Sorry, I can't help with that. I never actually used Ignition Gazebo myself. 
I just noticed that the controller can have stability issues in regular Gazebo when the simulation speed is too slow so I figured this might be the case here, as well.

**Comment by marco-tranzatto** [comment]
Hi @heuristicus 

Do you meet the specifications highlighted here: [recommended-system-setup](https://github.com/osrf/subt/wiki/System%20Requirements#recommended-system-setup) ?

You must have a discrete GPU card with at least 4GB of memory, otherwise simulation won't work.

**Comment by heuristicus** [comment]
Hi Marco,

I think that my system fulfills the recommended specs - but only just

```
Wed Apr 29 09:23:20 2020                                                                                                                                                                                            
+-----------------------------------------------------------------------------+                                                                                                                                     
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |                                                                                                                                     
|-------------------------------+----------------------+----------------------+                                                                                                                                     
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |                                                                                                                                     
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |                                                                                                                                     
|===============================+======================+======================|                                                                                                                                     
|   0  Quadro T2000        Off  | 00000000:01:00.0 Off |                  N/A |                                                                                                                                     
| N/A   51C    P5     8W /  N/A |    771MiB /  3911MiB |     36%      Default |                                                                                                                                     
+-------------------------------+----------------------+----------------------+
```

I haven't had a chance to check whether changing the real time factor makes a difference to the behaviour. Is the memory requirement due to tensorflow computations or loading/processing the environment map?

**Comment by marco-tranzatto** [comment]
These are requirements from the simulation environments required by the [subt](https://github.com/osrf/subt) simulation, so we can't to much about them. If you're system is not powerful enough, I'd suggest you try to reduce the real-time factor, or simulation speed, as suggested by Lorenz.

If you find a solution, please update this issue as it might be of interested of other people as well ;)

**Comment by Samu24** [comment]
@heuristicus I tested this on a PC which has adequate hardware and could reproduce your issue. We are restructuring things a bit and will provide a fix.

**Comment by heuristicus** [comment]
Thanks for the update - I will happily test the fix to see if it improves the situation on my machine.

**Comment by Samu24** [comment]
@heuristicus 
We have a fix and I opened a PR: #8.

If you want to test, make sure to use the branch `fix/controller` in the forked repo:
`git@github.com:leggedrobotics/subt_cerberus_anymal.git`

I would recommend to start with a fresh workspace since we changed some naming.

Let me know if you still have issues.

**Comment by heuristicus** [comment]
I've had a go at testing this and I'm still having the same issue. Perhaps I'm not setting things up correctly. Here's the procedure I followed:

Before doing this I deleted all my previous subt workspaces and did the full setup procedure again. After the initial setup I first merged the PR you made in the subt repository to the branch of the original cerberus models:

```
subt_ws/src/subt $ git branch
* model_pr_434
$ git remote add leggedrobotics git@github.com:leggedrobotics/subt_cerberus_anymal.git
$ git fetch leggedrobotics
$ git merge leggedrobotics/fix/controller
$ catkin_make install
```

Then, I checkout the fix PR for this repo:

```
anymal_locomotion_ws/src/cerberus_anymal_locomotion $ git branch
* master
$ git checkout fix/controller
$ catkin build
```

Both of these updates build without any problems.

Then, I run

```
ign launch -v 4 competition.ign robotName1:=anymal robotConfig1:=CERBERUS_ANYMAL_SENSOR_CONFIG_1 localModel:=true
```
to start the ignition simulation. I start the new controller with 

```
roslaunch cerberus_anymal_b_control_1 cerberus_anymal_controller.launch name:=anymal
```

And send a twist command with

```
rostopic pub /anymal/cmd_vel geometry_msgs/Twist "linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.2"
```

With those commands, the robot falls over after approximately the same amount of time as without the fix.

**Comment by Samu24** [comment]
`ign launch -v 4 competition.ign robotName1:=anymal robotConfig1:=CERBERUS_ANYMAL_SENSOR_CONFIG_1 localModel:=true` should not work. The config is `CERBERUS_ANYMAL_B_SENSOR_CONFIG_1`. If the previous worked you were still using the old config.

**Comment by Samu24** [comment]
Also which version of Eigen are you using.
You can get it via `pkg-config --modversion eigen3`

**Comment by heuristicus** [comment]
I tried again with the correct robotconfig and can confirm that the fix works on my machine.

Thanks very much.

(my eigen version is 3.3.4, although probably not relevant any more)

**Comment by Samu24** [comment]
Good to hear. Thanks for testing.
