### ISSUE TITLE
Controller cannot go up the hill or stop on the hill in the default subt map

### ISSUE THREAD

**Issue by heuristicus** [leggedrobotics/cerberus_anymal_locomotion#9]
I've been doing more testing on the subt system, and have noticed that the robot cannot stop or climb up the hill in the map that is loaded in the competition.ign launch file.

This can be verified by starting the robot at location something like position `(48, -1.5, -4.45)` and trying to go up the hill. The robot moves its legs but does not progress up at all. If you move the robot to the top of the hill and start it moving down, then try to stop, it will not stop.

**Comment by ArghyaChatterjee** [comment]
Hello @heuristicus , you seem to have worked on this project. However, I just wanted to know how to launch it in the predefined SubT world. 

I followed the tutorial provided in this repo. Everything works fine and I can launch the launch file ```roslaunch cerberus_anymal_b_control_1 cerberus_anymal_controller.launch``` and everything comes out smoothly in the terminal but I can't see any robot popping up in ignition-gazebo environment.

I have already setup the ignition-gazebo environment as described here: https://github.com/osrf/subt/wiki/Example%20Setup
The environment comes up smoothly when I mention the robot x1 and tunnel environment in flags like ```ign launch -v 4 tunnel_circuit_practice.ign robotName1:=X1 robotConfig1:=X1_SENSOR_CONFIG_1```. The x1 robot seem to be successfully spawned and I can run the x1 robot with controller in the tunnel circuit environment.
 
So what wrong is taking place in my case? I am trying to launch the environment:
``` ign launch -v 4 tunnel_circuit_practice.ign``` & then in another terminal (environment sourced) ```roslaunch cerberus_anymal_b_control_1 cerberus_anymal_controller.launch```. Both of them individually launched very well but the anymal robot doesn't seem to be spawned in the tunnel circuit environment.

Can you please help me?

**Comment by marco-tranzatto** [comment]
Hi @ArghyaChatterjee 

Can you try out the instructions here: [Usage Instructions](https://github.com/osrf/subt/blob/master/submitted_models/cerberus_anymal_b_sensor_config_1/specifications.md#usage-instructions) ?

Marco

**Comment by Samu24** [comment]
Hi @ArghyaChatterjee 

Keep in mind that the first startup takes a bit more time since you have to download all the models to your local machine.

**Comment by Samu24** [comment]
Regarding the original post of @heuristicus:
Keep in mind that this is a blind locomotion controller. It is likely that it can not handle all terrains equally well, especially going up might be difficult as it does not know how high the feet need to be lifted. Furthermore, if you walk down and the robot can not hold its position with zero velocity because it would fall, it will keep walking.

Moreover, we had to add noise to the topics we use in the controller as we would publish ground truth information to ROS otherwise which is not allowed. This decreased performance of the controller.
